services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: eventschedulingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"